### ISSUE TITLE
Cooler.py referencing HGOM instead of CGOM

### ISSUE THREAD

**Issue by dpeluso** [funtastix/pyrinnaitouch#1]
I could be wrong, however the Cooler.py referencing HGOM instead of what I believe should  CGOM is causing an error to be thrown on my setup.

https://github.com/funtastix/pyrinnaitouch/blob/13dbec80306fb0880906f6bfb44a2a55b1f8a111/pyrinnaitouch/cooler.py#L67

**Comment by funtastix** [comment]
You are absolutely correct. Unfortunately, I don't actually have a refrigerated unit, so I was never able to fully test this. Should be an easy update. Stand By.

**Comment by dpeluso** [comment]
WoW that was quick @funtastix !!! I've deployed the develop branch on my HomeAssistant and so far it looks like i'm back up and running, thanks for the amazing turnaround!!

**Comment by funtastix** [comment]
I've released an updated version of the library (0.9.3) and the rinnai module for HA: https://github.com/funtastix/rinnaitouch/releases/tag/0.10.2
